server:
  port: 8081

proxy:
  dashscope-base-url: "https://dashscope.aliyuncs.com"
  dashscope-api-key: "${DASHSCOPE_API_KEY:}"
  dashscope-model: "qwen-image-max"
  require-openai-key: false
  openai-key: "${OPENAI_IMAGE_PROXY_KEY:}"
  prompt-extend: true
  watermark: false # true 会导致图片模糊
